// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKS1leE5bthF6GH3zYo_ICSMiV_gOVTEE',
    appId: '1:693712102921:web:fc88b3cb01e95f07b2bad8',
    messagingSenderId: '693712102921',
    projectId: 'noteshare-86d6d',
    authDomain: 'noteshare-86d6d.firebaseapp.com',
    storageBucket: 'noteshare-86d6d.firebasestorage.app',
    measurementId: 'G-KYF5Z2NRFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfDaAVWK5Wtj2osJxuRz1dFLQrV5kFPNQ',
    appId: '1:693712102921:android:e649e82642967284b2bad8',
    messagingSenderId: '693712102921',
    projectId: 'noteshare-86d6d',
    storageBucket: 'noteshare-86d6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnUlVefWMF_GF_TeFs01BIUytKGj83RQE',
    appId: '1:693712102921:ios:faae095156aa81eab2bad8',
    messagingSenderId: '693712102921',
    projectId: 'noteshare-86d6d',
    storageBucket: 'noteshare-86d6d.firebasestorage.app',
    iosBundleId: 'com.example.noteshareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnUlVefWMF_GF_TeFs01BIUytKGj83RQE',
    appId: '1:693712102921:ios:faae095156aa81eab2bad8',
    messagingSenderId: '693712102921',
    projectId: 'noteshare-86d6d',
    storageBucket: 'noteshare-86d6d.firebasestorage.app',
    iosBundleId: 'com.example.noteshareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKS1leE5bthF6GH3zYo_ICSMiV_gOVTEE',
    appId: '1:693712102921:web:60c36ad3eee49ec6b2bad8',
    messagingSenderId: '693712102921',
    projectId: 'noteshare-86d6d',
    authDomain: 'noteshare-86d6d.firebaseapp.com',
    storageBucket: 'noteshare-86d6d.firebasestorage.app',
    measurementId: 'G-F3LQC0MWN0',
  );
}
